/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SlModal {
        "header": string;
        "open": boolean;
    }
}
declare global {
    interface HTMLSlModalElement extends Components.SlModal, HTMLStencilElement {
    }
    var HTMLSlModalElement: {
        prototype: HTMLSlModalElement;
        new (): HTMLSlModalElement;
    };
    interface HTMLElementTagNameMap {
        "sl-modal": HTMLSlModalElement;
    }
}
declare namespace LocalJSX {
    interface SlModal {
        "header"?: string;
        "open"?: boolean;
    }
    interface IntrinsicElements {
        "sl-modal": SlModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sl-modal": LocalJSX.SlModal & JSXBase.HTMLAttributes<HTMLSlModalElement>;
        }
    }
}
